logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

security:
  user:
    password: secret

server:
  port: 8081

spring:
  main:
    show_banner: false
