endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    server:
      paths: /remote-hello/greet

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level.: WARN

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  context-path: /remote-hello
  port: 8081

spring:
  main:
    show_banner: false
