logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

management:
  context-path: /manage

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  port: 8081

spring:
  main:
    show_banner: false
