endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    server:
      paths: /config/**

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level.: WARN

management:
  context-path: /admin

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          basedir: target/config
          uri: file:///Users/boxley/src/java//simple-boot-config
  main:
    show_banner: false
