datasource:
  bob:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:bob;DB_CLOSE_ON_EXIT=FALSE'
  nancy:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:nancy;DB_CLOSE_ON_EXIT=FALSE'
  wick-fowler:
    driverClassName: org.h2.Driver
    url: 'jdbc:h2:mem:tasty-chili;DB_CLOSE_ON_EXIT=FALSE'

endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    client:
      paths: /remote-hello/greet
    server:
      paths: /hello-world/hello/*

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level.: WARN

remote-hello:
  ribbon:
    listOfServers: bad-host:4444, localhost:8081

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  context-path: /hello-world
  port: 8080

spring:
  main:
    show_banner: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

# TODO: Address Spring filtering
swagger:
  api:
    title: Simple Boot
    description: Simple examples for Spring Boot
    contact:
      email-address: binkley@alumni.rice.edu
    license:
      name: Public Domain # @project.licenses[0].name@
      url: http://unlicense.org/UNLICENSE # @project.licenses[0].url@
