logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

security:
  # TODO: Can path match be inverted, i.e. all BUT /manage?
  ignored: /hello
  user:
    password: secret

server:
  port: 8080

spring:
  main:
    show_banner: false
