endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    paths: /hello/*

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

security:
  basic:
    enabled: false
  user:
    password: secret

remote-hello:
  ribbon:
    listOfServers: localhost:8081

server:
  port: 8080

spring:
  main:
    show_banner: false
