endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    paths: /hello/*

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

remote-hello:
  ribbon:
    listOfServers: localhost:8081

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  port: 8080

spring:
  main:
    show_banner: false

# TODO: Address Spring filtering
swagger:
  api:
    title: Simple Boot
    description: Simple examples for Spring Boot
    contact:
      email-address: me@there.xxx
    license:
      name: Public Domain # @project.licenses[0].name@
      url: http://unlicense.org/UNLICENSE # @project.licenses[0].url@
