logging:
  level:
    com.mangofactory: WARN
    com.netflix: WARN
    io.undertow: WARN
    org.springframework: WARN
    org.xnio: WARN

server:
  port: 8080

spring:
  main:
    show_banner: false
