endpoints:
  health:
    sensitive: false

headers:
  correlation-id:
    client:
      paths: /remote-hello/greet
    server:
      paths: /hello-world/hello/*

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  level.: WARN

remote-hello:
  ribbon:
    listOfServers: bad-host:4444, localhost:8081

security:
  basic:
    enabled: false
  user:
    password: secret

server:
  context-path: /hello-world
  port: 8080

spring:
  datasource:
    # Spring Boot managed d/b lifecycle
    url: 'jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE'
  main:
    show_banner: false
  jpa:
    database: H2

# TODO: Address Spring filtering
swagger:
  api:
    title: Simple Boot
    description: Simple examples for Spring Boot
    contact:
      email-address: binkley@alumni.rice.edu
    license:
      name: Public Domain # @project.licenses[0].name@
      url: http://unlicense.org/UNLICENSE # @project.licenses[0].url@
